name: theSfiles
favicon: null
layout_spectrum: 0.24961
typography_spectrum: 0.75352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#14285a'
    - '#9d9ea0'
    - '#5d687a'
    - '#e1b83a'
  brandStrength: 0.5
  lightness: 0.46309785451740026
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
