title: theSharingFiles
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1875
  lightness: 0.4630978545174003
  brandStrength: 0
  brandColors:
    - '#03060D'
    - '#DFD0A2'
    - '#543938'
    - '#FEFEF3'
    - '#916E53'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: theSfiles
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.75352
layout_spectrum: 0.24961
