name: theSfiles
favicon: null
layout_spectrum: 0.24961
typography_spectrum: 0.75352
title: theSharingFiles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c5dbce'
    - '#404644'
    - '#7ea6a8'
    - '#9b2639'
  brandStrength: 0.5
  lightness: 0.46309785451740026
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
